//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dionysus.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dionysus.Localization.strings.fr", typeof(strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez le fichier &quot;.exe&quot;.
        /// </summary>
        internal static string AddGameForm_SelectorLabel {
            get {
                return ResourceManager.GetString("AddGameForm-SelectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom (en anglais).
        /// </summary>
        internal static string AddGameForm_TitlePlaceholder {
            get {
                return ResourceManager.GetString("AddGameForm-TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string EditGameForm_CoverLabel {
            get {
                return ResourceManager.GetString("EditGameForm-CoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien de l&apos;image.
        /// </summary>
        internal static string EditGameForm_CoverPlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-CoverPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options de lancement.
        /// </summary>
        internal static string EditGameForm_LaunchOptionsLabel {
            get {
                return ResourceManager.GetString("EditGameForm-LaunchOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier les options de lancement.
        /// </summary>
        internal static string EditGameForm_LaunchOptionsPlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-LaunchOptionsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin.
        /// </summary>
        internal static string EditGameForm_LocationLabel {
            get {
                return ResourceManager.GetString("EditGameForm-LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du fichier.
        /// </summary>
        internal static string EditGameForm_LocationPlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-LocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string EditGameForm_TitleLabel {
            get {
                return ResourceManager.GetString("EditGameForm-TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le nom du jeu.
        /// </summary>
        internal static string EditGameForm_TitlePlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter à la bibliothèque.
        /// </summary>
        internal static string GamesPage_AddToLibTitle {
            get {
                return ResourceManager.GetString("GamesPage-AddToLibTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        internal static string GamesPage_DownloadTitle {
            get {
                return ResourceManager.GetString("GamesPage-DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le nom du jeu....
        /// </summary>
        internal static string GamesPage_SearchPanelPlaceholder {
            get {
                return ResourceManager.GetString("GamesPage-SearchPanelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier par.
        /// </summary>
        internal static string HomePage_SortBy {
            get {
                return ResourceManager.GetString("HomePage-SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeu archivé.
        /// </summary>
        internal static string LibraryPage_ArchivedGame {
            get {
                return ResourceManager.GetString("LibraryPage-ArchivedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vide.
        /// </summary>
        internal static string MainPage_EmptyError {
            get {
                return ResourceManager.GetString("MainPage-EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeux.
        /// </summary>
        internal static string ProfileData_GamesCount {
            get {
                return ResourceManager.GetString("ProfileData-GamesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total joué.
        /// </summary>
        internal static string ProfileData_TotalPlayed {
            get {
                return ResourceManager.GetString("ProfileData-TotalPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter au démarrage.
        /// </summary>
        internal static string SettingsPage_AddToStartup {
            get {
                return ResourceManager.GetString("SettingsPage-AddToStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string SettingsPage_ApplicationSeparator {
            get {
                return ResourceManager.GetString("SettingsPage-ApplicationSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde automatique.
        /// </summary>
        internal static string SettingsPage_AutoBackup {
            get {
                return ResourceManager.GetString("SettingsPage-AutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vérifier.
        /// </summary>
        internal static string SettingsPage_CheckSources {
            get {
                return ResourceManager.GetString("SettingsPage-CheckSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string SettingsPage_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPage-LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothèque.
        /// </summary>
        internal static string SettingsPage_LibrarySeparator {
            get {
                return ResourceManager.GetString("SettingsPage-LibrarySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une sauvegarde.
        /// </summary>
        internal static string SettingsPage_MakeBackup {
            get {
                return ResourceManager.GetString("SettingsPage-MakeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string SettingsPage_ProfileImageLabel {
            get {
                return ResourceManager.GetString("SettingsPage-ProfileImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string SettingsPage_ProfileSeparator {
            get {
                return ResourceManager.GetString("SettingsPage-ProfileSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurer la sauvegarde.
        /// </summary>
        internal static string SettingsPage_RestoreBackup {
            get {
                return ResourceManager.GetString("SettingsPage-RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une image.
        /// </summary>
        internal static string SettingsPage_SelectImage {
            get {
                return ResourceManager.GetString("SettingsPage-SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le lien vers la page du jeu sélectionné.
        /// </summary>
        internal static string SettingsPage_Setting1 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la version du jeu (ne fonctionne pas avec tous les repacks).
        /// </summary>
        internal static string SettingsPage_Setting2 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la date de l&apos;enregistrement du torrent (ne fonctionne pas avec gog).
        /// </summary>
        internal static string SettingsPage_Setting3 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éviter la conversion du fichier torrent en lien magnétique.
        /// </summary>
        internal static string SettingsPage_Setting4 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le titre du jeu.
        /// </summary>
        internal static string SettingsPage_ShowGameTitle {
            get {
                return ResourceManager.GetString("SettingsPage-ShowGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le dernier temps d’exécution.
        /// </summary>
        internal static string SettingsPage_ShowLastRunTime {
            get {
                return ResourceManager.GetString("SettingsPage_ShowLastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string SettingsPage_SourcesLabel {
            get {
                return ResourceManager.GetString("SettingsPage-SourcesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        internal static string SettingsPage_ThemeLabel {
            get {
                return ResourceManager.GetString("SettingsPage-ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string SettingsPage_TorrentSeparator {
            get {
                return ResourceManager.GetString("SettingsPage-TorrentSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        internal static string SettingsPage_UsernameLabel {
            get {
                return ResourceManager.GetString("SettingsPage-UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le nom d&apos;utilisateur....
        /// </summary>
        internal static string SettingsPage_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("SettingsPage-UsernamePlaceholder", resourceCulture);
            }
        }
    }
}
