//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dionysus.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dionysus.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;.exe&quot; file.
        /// </summary>
        internal static string AddGameForm_SelectorLabel {
            get {
                return ResourceManager.GetString("AddGameForm-SelectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (English).
        /// </summary>
        internal static string AddGameForm_TitlePlaceholder {
            get {
                return ResourceManager.GetString("AddGameForm-TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string EditGameForm_CoverLabel {
            get {
                return ResourceManager.GetString("EditGameForm-CoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit cover url.
        /// </summary>
        internal static string EditGameForm_CoverPlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-CoverPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch options.
        /// </summary>
        internal static string EditGameForm_LaunchOptionsLabel {
            get {
                return ResourceManager.GetString("EditGameForm-LaunchOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit options.
        /// </summary>
        internal static string EditGameForm_LaunchOptionsPlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-LaunchOptionsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string EditGameForm_LocationLabel {
            get {
                return ResourceManager.GetString("EditGameForm-LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        internal static string EditGameForm_LocationPlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-LocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EditGameForm_TitleLabel {
            get {
                return ResourceManager.GetString("EditGameForm-TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit title.
        /// </summary>
        internal static string EditGameForm_TitlePlaceholder {
            get {
                return ResourceManager.GetString("EditGameForm-TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to library.
        /// </summary>
        internal static string GamesPage_AddToLibTitle {
            get {
                return ResourceManager.GetString("GamesPage-AddToLibTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string GamesPage_DownloadTitle {
            get {
                return ResourceManager.GetString("GamesPage-DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type game name....
        /// </summary>
        internal static string GamesPage_SearchPanelPlaceholder {
            get {
                return ResourceManager.GetString("GamesPage-SearchPanelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string HomePage_SortBy {
            get {
                return ResourceManager.GetString("HomePage-SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived game.
        /// </summary>
        internal static string LibraryPage_ArchivedGame {
            get {
                return ResourceManager.GetString("LibraryPage-ArchivedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string MainPage_EmptyError {
            get {
                return ResourceManager.GetString("MainPage-EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string ProfileData_GamesCount {
            get {
                return ResourceManager.GetString("ProfileData-GamesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total played.
        /// </summary>
        internal static string ProfileData_TotalPlayed {
            get {
                return ResourceManager.GetString("ProfileData-TotalPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to startup.
        /// </summary>
        internal static string SettingsPage_AddToStartup {
            get {
                return ResourceManager.GetString("SettingsPage-AddToStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string SettingsPage_ApplicationSeparator {
            get {
                return ResourceManager.GetString("SettingsPage-ApplicationSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-backup.
        /// </summary>
        internal static string SettingsPage_AutoBackup {
            get {
                return ResourceManager.GetString("SettingsPage-AutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string SettingsPage_CheckSources {
            get {
                return ResourceManager.GetString("SettingsPage-CheckSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsPage_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPage-LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string SettingsPage_LibrarySeparator {
            get {
                return ResourceManager.GetString("SettingsPage-LibrarySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make backup.
        /// </summary>
        internal static string SettingsPage_MakeBackup {
            get {
                return ResourceManager.GetString("SettingsPage-MakeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string SettingsPage_ProfileImageLabel {
            get {
                return ResourceManager.GetString("SettingsPage-ProfileImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string SettingsPage_ProfileSeparator {
            get {
                return ResourceManager.GetString("SettingsPage-ProfileSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup.
        /// </summary>
        internal static string SettingsPage_RestoreBackup {
            get {
                return ResourceManager.GetString("SettingsPage-RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        internal static string SettingsPage_SelectImage {
            get {
                return ResourceManager.GetString("SettingsPage-SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show link to the page of the selected game.
        /// </summary>
        internal static string SettingsPage_Setting1 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show game version (not all repacks are being worked on).
        /// </summary>
        internal static string SettingsPage_Setting2 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show torrent post date (gog not working).
        /// </summary>
        internal static string SettingsPage_Setting3 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid converting the torrent file to a magnet link.
        /// </summary>
        internal static string SettingsPage_Setting4 {
            get {
                return ResourceManager.GetString("SettingsPage-Setting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show game title.
        /// </summary>
        internal static string SettingsPage_ShowGameTitle {
            get {
                return ResourceManager.GetString("SettingsPage-ShowGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the last run time.
        /// </summary>
        internal static string SettingsPage_ShowLastRunTime {
            get {
                return ResourceManager.GetString("SettingsPage_ShowLastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string SettingsPage_SourcesLabel {
            get {
                return ResourceManager.GetString("SettingsPage-SourcesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsPage_ThemeLabel {
            get {
                return ResourceManager.GetString("SettingsPage-ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string SettingsPage_TorrentSeparator {
            get {
                return ResourceManager.GetString("SettingsPage-TorrentSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SettingsPage_UsernameLabel {
            get {
                return ResourceManager.GetString("SettingsPage-UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type username....
        /// </summary>
        internal static string SettingsPage_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("SettingsPage-UsernamePlaceholder", resourceCulture);
            }
        }
    }
}
